ifeq ($(CONFIG_SOC_EXYNOS7885_ANDROID_VERSION_P),y)
dtb-$(CONFIG_MACH_EXYNOS7885_A20E_OPEN) := \
	exynos7884B-a20e_kor_ktt_00.dtbo \
	exynos7884B-a20e_eur_open_00.dtbo \
	exynos7884B-a20e_eur_open_03.dtbo
endif
